=== crocdigital/lewrap/.astro/collections/popups.schema.json
{
  "$ref": "#/definitions/popups",
  "definitions": {
    "popups": {
      "type": "object",
      "properties": {
        "popup_id": {
          "type": "string",
          "enum": [
            "newsletter_modal",
            "franchise_enquiry"
          ]
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "image": {
          "type": "string"
        },
        "image_position": {
          "type": "string"
        },
        "show_on_load": {
          "type": "boolean",
          "default": false
        },
        "remember_close": {
          "type": "boolean",
          "default": false
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "popup_id",
        "title",
        "description"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== crocdigital/lewrap/src/content/popups/newsletter.json
{
    "popup_id": "newsletter_modal",
    "title": "Sign up to our Loyalty Program",
    "description": "<p>Subscribe to our newsletter for exclusive offers, new menu items, and updates!</p>",
    "image": "/images/elements/baguette-beef.webp",
    "image_position": "w-28 md:w-36 h-auto absolute left-1/2 -translate-x-1/2 -top-9 md:-top-19",
    "show_on_load": true,
    "remember_close": true
}
